name: Workflow CI

on:
  push:
    branches: [ main ]

jobs:
  run_training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 dagshub pandas scikit-learn joblib

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/Chanie-ago/liver-disease-mlflow.mlflow
        run: |
          cd MLProject
          # Menjalankan training dengan environment lokal runner
          mlflow run . --env-manager local

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: liver-model-artifacts
          path: MLProject/