name: Workflow CI

on:
  push:
    branches: [ main ]

jobs:
  training_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 dagshub pandas scikit-learn

      - name: Run MLflow Training
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/Chanie-ago/liver-disease-mlflow.mlflow
        run: |
          cd MLProject
          # Jalankan training menggunakan env lokal runner
          mlflow run . --env-manager local

      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: liver-disease-model
          path: |
            MLProject/mlruns/
            # Menyimpan folder mlruns agar model bisa di-download lewat GitHub